version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: root
      POSTGRES_DB: ice_cream

  adminer:
    image: adminer
    restart: always
    ports:  
      - 8081:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6380:6379

  
volumes:
  postgres_data: